name: Install debian package

on:
  push:

jobs:
  test-deb-install:
    runs-on: ubuntu-22.04
    env:
      PGPASSWORD: postgres  # No password prompt

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y docker.io containerd runc
          docker run -d --rm --name postgres-db -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=postgres -d postgres && sleep 10

      - name: Prepare postgres service Rocky
        run: |
          createdb -h localhost -U postgres rocky_db
          createuser -h localhost -U postgres rocky
          psql -h localhost -U postgres -d rocky_db -c "GRANT ALL ON DATABASE rocky_db TO rocky;"
          psql -h localhost -U postgres -d rocky_db -c "ALTER USER rocky WITH PASSWORD 'postgres';" 

      - name: Get the artifacts
        run: |
          mkdir openkat 
          curl -Ls https://github.com/minvws/nl-kat-coordination/releases/download/v1.5.2/kat-ubuntu22.04-1.5.2.tar.gz --output kat-ubuntu22.04-1.5.2.tar.gz;
          curl -Ls https://github.com/dekkers/xtdb-http-multinode/releases/download/v1.0.2/xtdb-http-multinode_1.0.2_all.deb --output xtdb-http-multinode_1.0.2_all.deb;

      - name: Unpack and install the artifacts
        run: |
          tar zvxf kat-*.tar.gz
          sudo apt install ./kat-*_amd64.deb ./xtdb-http-multinode_*_all.deb

      - name: Migrations for Rocky
        run: |
          sudo sed -i "s/ROCKY_DB_PASSWORD=/ROCKY_DB_PASSWORD=postgres/g" /etc/kat/rocky.conf
          sudo -u kat rocky-cli migrate
          sudo -u kat rocky-cli loaddata /usr/share/kat-rocky/OOI_database_seed.json
