name: Install debian package

on:
  push:

jobs:
  test-deb-install:
    strategy:
      matrix:
        dist: [ debian11, ubuntu22.04 ]
    runs-on: ubuntu-22.04
    env:
      PGPASSWORD: postgres  # No password prompt

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Get the artifacts
        run: curl -Ls https://github.com/minvws/nl-kat-coordination/releases/download/v1.5.2/kat-${{ matrix.dist }}-1.5.2.tar.gz;

      - name: Unpack and install the artifacts
        run: |
          tar zvxf kat-*.tar.gz
          apt install --no-install-recommends ./kat-*_amd64.deb ./xtdb-http-multinode_*_all.deb

      - name: Prepare postgres service Rocky
        run: |
          apt install -y postgresql-client
          createdb -h postgres -U postgres rocky_db
          createuser -h postgres -U postgres rocky
          psql -h postgres -U postgres -d rocky_db -c 'GRANT ALL ON DATABASE rocky_db TO rocky;'  

      - name: Migrations for Rocky
        run: |
          rocky-cli migrate
          rocky-cli loaddata /usr/share/kat-rocky/OOI_database_seed.json
